In [21]:
import numpy as np

In [22]:
the_array= np.array([1,7,2,0,-1])

#insert
x= int(input('Element to add: '))
the_array=np.append(the_array,x)
print(the_array)




Element to add: 4
[ 1  7  2  0 -1  4]


In [23]:
#delete
y= int(input('Element to delete: '))
the_array=the_array[the_array!=y]
print(the_array)

Element to delete: 7
[ 1  2  0 -1  4]


In [24]:
maxx=np.max(the_array)
minn=np.min(the_array)

print(f'Maximum: {maxx}')
print(f'Minimum: {minn}')


Maximum: 4
Minimum: -1


In [27]:
#reverse
print(the_array[::-1])

[ 4 -1  0  2  1]


In [31]:
#2nd largest
sorted= np.sort(the_array)
print(sorted)
print(sorted[-2])

[-1  0  1  2  4]
2


In [41]:
#2D
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
#operations

matrix2=np.array([[7,3,9],[2,5,6],[8,1,-6]])
addi=np.add(matrix1,matrix2)
multi=np.multiply(matrix1,matrix2)
matmulti=np.matmul(matrix1,matrix2)
transpose1=np.transpose(matrix1)
print(f'Addition:\n {addi}')
print(f'Multiply:\n {multi}')
print(f'Matrix Multiplication:\n {matmulti}')
print(f'Transpose of Matrix1:\n {transpose1}')


Addition:
 [[ 8  5 12]
 [ 6 10 12]
 [15  9  3]]
Multiply:
 [[  7   6  27]
 [  8  25  36]
 [ 56   8 -54]]
Matrix Multiplication:
 [[ 35  16   3]
 [ 86  43  30]
 [137  70  57]]
Transpose of Matrix1:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
